apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2022-05-28 - 19:09:17 +0000
  labels:
    app.kubernetes.io/name: kubernetes-quickstart
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    manager: okhttp
    operation: Update
  name: kubernetes-quickstart
  namespace: default
spec:
  ports:
  - name: http
    nodePort: 30068
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: kubernetes-quickstart
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  sessionAffinity: None
  type: LoadBalancer

